---
# handlers file for ansible-role-nagios-config-deploy

- name: nagios find repo base files
  find:
    paths: "{{ nagios_config_deploy_base_src }}"
    patterns: "*.cfg"
  register: find_base

- name: nagios symlink repo base files
  file:
    src: "{{ nagios_config_deploy_base_src }}{{ item.path | basename }}"
    dest: "{{ nagios_config_deploy_nagios_path }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_base.files }}"
  notify: nagios reload

- name: nagios find repo override files
  find:
    paths: "{{ nagios_config_deploy_or_src }}"
    patterns: "*.cfg"
  register: find_override

- name: nagios symlink repo override files
  file:
    src: "{{ nagios_config_deploy_or_src }}{{ item.path | basename }}"
    dest: "{{ nagios_config_deploy_nagios_path }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_override.files }}"
  notify: nagios reload

- name: nagios check repo plugin files
  find:
    paths: "{{ nagios_config_deploy_plug_src }}"
    patterns: "*"
  register: find_plugins

- name: nagios symlink repo plugin files
  file:
    src: "{{ nagios_config_deploy_plug_src }}{{ item.path | basename }}"
    dest: "{{ nagios_config_deploy_plugins_path }}{{ item.path | basename }}"
    state: link
    force: yes
  notify: nagios reload

- name: nagios reload
  service: name=nagios state=restarted
